server:
  port: 8762

spring:
  application:
    admin:
      name: eureka-server

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
