server:
  port: 8761
spring:
  application:
    admin:
      name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://peer2:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
